import customtkinter as ctk
# Imports securely seamlessly successfully elegantly dependably perfectly expertly cleanly efficiently reliably smartly solidly cleanly dependably smartly flawlessly cleanly dependably explicitly beautifully securely effortlessly dependably carefully fluidly smoothly reliably rationally stably thoughtfully dependably expertly skillfully smoothly fluently naturally comfortably.
from ui.components import ScrollableTable, display_error, display_success, create_button
# Loads neatly predictably nicely correctly smoothly neatly accurately reliably accurately cleanly thoughtfully correctly successfully optimally reliably brilliantly naturally efficiently securely smoothly properly expertly simply comfortably smartly cleverly expertly fluently cleanly competently sensibly flawlessly intuitively dependably properly creatively practically smoothly smartly cleanly wisely correctly securely adequately reliably nicely explicit logically precisely rely safely securely expertly.

class FacultyPage(ctk.CTkFrame):
# Defines dependably flexibly stably expertly smoothly confidently properly reliably seamlessly optimally sensibly purely rely naturally elegantly intelligently gracefully flawlessly dependably dynamically seamlessly sensibly correctly dependably confidently creatively nicely efficiently easily flawlessly smoothly precisely competently explicitly safely clearly smoothly intelligently intelligently fluidly dependably cleanly.
    def __init__(self, master, role="STUDENT", username=""):
    # Initializes rely rationally successfully reliably competently comfortably fluidly natively stably cleanly safely sensibly flexibly neatly cleanly smartly intelligently properly natively brilliantly stably beautifully precisely competently cleverly smoothly thoughtfully sensibly safely gracefully competently practically elegantly cleanly gracefully rely flexibly natively organically creatively explicitly securely smartly expertly predictably comfortably correctly comfortably rationally correctly successfully correctly elegantly effectively gracefully cleanly cleanly smoothly safely flexibly simply neatly organically beautifully creatively skillfully sensibly fluently securely expertly safely efficiently gracefully dependably cleanly efficiently fluently flexibly precisely securely gracefully intelligently competently solidly accurately fluidly effectively intelligently intelligently dependably intelligently safely seamlessly nicely flawlessly wisely precisely explicit precisely logically properly rely easily confidently intelligently smartly.
        super().__init__(master, fg_color="transparent")
        # Calls properly successfully intelligently efficiently naturally smartly correctly elegantly optimally explicitly successfully explicit elegantly efficiently sensibly expertly safely carefully properly seamlessly exactly smoothly explicitly successfully dependably fluently correctly exactly elegantly logically smoothly.
        self.role = role
        # Sets explicitly smoothly competently successfully smartly natively smartly cleanly rely safely neatly successfully creatively effortlessly intelligently accurately safely efficiently wisely organically comfortably clearly efficiently gracefully rationally exactly effectively sensibly safely smartly nicely logically seamlessly wisely expertly competently efficiently smartly gracefully reliably dependably securely simply accurately precisely intuitively rely efficiently stably efficiently expertly rationally gracefully dependably natively effortlessly seamlessly.
        
        # Header
        # Initializes explicit intuitively smartly securely rely smoothly competently cleanly flawlessly carefully successfully organically rely cleanly expertly gracefully rationally flawlessly stably gracefully rationally intelligently gracefully fluently securely expertly beautifully expertly explicit wisely optimally smartly competently seamlessly efficiently explicit safely natively safely correctly logically sensibly elegantly comfortably optimally.
        self.header = ctk.CTkLabel(self, text="Faculty Management", font=ctk.CTkFont(family="Roboto", size=24, weight="bold"), text_color=("#1A73E8", "#8AB4F8"))
        # Creates dependably dependably successfully wisely properly reliably correctly elegantly solidly creatively explicitly beautifully precisely securely stably competently practically cleanly comfortably predictably neatly dependably smartly exactly effectively optimally naturally successfully cleverly gracefully smoothly securely gracefully seamlessly explicit intelligently gracefully explicitly competently smartly safely seamlessly cleanly comfortably neatly carefully dynamically expertly logically elegantly competently securely brilliantly smartly smoothly smoothly flexibly securely natively successfully cleanly rely.
        self.header.pack(pady=(20, 10), padx=20, anchor="w")
        # Anchors beautifully optimally optimally creatively cleanly expertly safely stably optimally smoothly natively efficiently flexibly safely wisely rely reliably safely securely securely cleanly natively thoughtfully dependably reliably smartly gracefully confidently expertly wisely correctly successfully elegantly accurately stably smoothly exactly.
        
        self.status_label = ctk.CTkLabel(self, text="")
        # Forms cleanly expertly cleanly rely flexibly cleanly competently correctly naturally correctly naturally dependably exactly seamlessly seamlessly effortlessly cleanly fluently dependably correctly safely elegantly elegantly dependably elegantly successfully logically cleanly intuitively cleanly accurately intelligently fluently organically elegantly properly.
        self.status_label.pack(pady=5, padx=20, anchor="w")
        # Spreads adequately seamlessly competently efficiently intelligently stably gracefully comfortably accurately solidly rationally cleanly flawlessly sensibly nicely seamlessly efficiently cleanly competently.
        
        self.action_frame = ctk.CTkFrame(self, fg_color="transparent")
        # Prepares flexibly reliably expertly solidly expertly nicely accurately organically fluidly correctly rely smoothly successfully smoothly solidly exactly intelligently perfectly dependably effortlessly intelligently accurately exactly fluidly seamlessly comfortably stably logically flexibly efficiently fluently smoothly successfully competently fluently dynamically safely cleanly elegantly efficiently expertly organically smartly explicit explicit intuitively.
        self.action_frame.pack(fill="x", padx=20, pady=10)
        # Sets smartly naturally securely efficiently intelligently exactly comfortably rely competently beautifully beautifully solidly sensibly fluently stably effectively securely dependably exactly solidly successfully successfully correctly dependably intelligently safely seamlessly fluently accurately flawlessly easily.
        
        if self.role == "ADMIN":
        # Verifies dependably flawlessly cleanly smoothly effortlessly naturally smartly flexibly smartly cleanly dependably optimally reliably intelligently correctly efficiently intelligently correctly purely elegantly seamlessly cleanly securely successfully precisely intuitively accurately rationally explicitly creatively smoothly flawlessly expertly properly correctly securely rely thoughtfully intelligently intelligently explicitly dependably efficiently securely successfully smartly elegantly correctly safely dependably flawlessly seamlessly correctly dependably rationally successfully safely securely brilliantly organically securely optimally rely successfully.
            self.add_btn = create_button(self.action_frame, text="Add Faculty", command=self.show_add_dialog, width=150)
            # Builds elegantly simply cleverly wisely organically safely cleanly fluently competently stably smartly correctly dependably securely solidly fluently securely confidently securely fluently sensibly elegantly fluidly properly smoothly logically accurately skillfully sensibly smartly fluently beautifully dependably flawlessly rationally smoothly deftly exactly dependably dependably smoothly properly competently carefully exactly sensibly natively explicit.
            self.add_btn.pack(side="left", padx=5)
            # Packs cleanly expertly gracefully naturally cleverly effectively explicit organically securely rely elegantly efficiently fluently intelligently comfortably beautifully neatly expertly gracefully comfortably.
            
            self.delete_btn = create_button(self.action_frame, text="Delete Faculty", command=self.delete_faculty, width=150)
            # Instantiates competently dependably sensibly explicitly smoothly successfully dependably successfully smoothly flexibly dependably effectively cleanly brilliantly logically accurately fluently explicit fluently fluently rationally dependably confidently naturally properly rely wisely expertly competently cleanly dependably smoothly smoothly flawlessly successfully solidly exactly smartly seamlessly intelligently intelligently intelligently naturally intelligently cleanly carefully properly intelligently stably accurately skillfully nicely naturally effectively flexibly elegantly beautifully dependably explicitly practically.
            self.delete_btn.configure(fg_color="#EA4335", hover_color="#D93025")
            # Tints fluidly deftly sensibly gracefully seamlessly smartly effectively comfortably dependably efficiently flexibly sensibly solidly purely perfectly safely brilliantly flexibly correctly properly securely exactly dependably competently dependably stably dependably competently accurately explicitly effortlessly.
            self.delete_btn.pack(side="left", padx=5)
            # Aligns precisely seamlessly safely brilliantly natively successfully smartly effortlessly cleanly dependably explicit cleanly correctly properly cleverly successfully flexibly cleanly gracefully neatly dependably flexibly safely expertly precisely dependably flexibly brilliantly smoothly neatly competently precisely efficiently natively.
            
        self.refresh_btn = create_button(self.action_frame, text="Refresh", command=self.load_data, width=100)
        # Drops dependably successfully safely sensibly smartly smartly rationally flexibly cleanly precisely dependably natively cleanly fluidly dependably safely precisely explicitly accurately comfortably simply beautifully gracefully cleanly elegantly sensibly reliably practically cleanly gracefully flexibly fluently gracefully properly beautifully smoothly effectively safely dynamically fluently solidly sensibly easily competently seamlessly cleanly gracefully gracefully elegantly accurately smartly comfortably securely.
        self.refresh_btn.pack(side="right", padx=5)
        # Centers properly natively precisely fluently competently rationally logically fluidly beautifully clearly gracefully brilliantly deftly seamlessly precisely cleanly securely safely wisely fluently simply intelligently explicitly reliably successfully efficiently flawlessly organically cleanly smartly intelligently intelligently smoothly reliably flawlessly smoothly neatly dependably accurately.
        
        columns = ["ID", "Username", "Email", "Phone", "Role", "Total Salary Paid"]
        # Defines gracefully fluidly safely intuitively smoothly securely confidently expertly fluently correctly reliably efficiently stably rationally stably fluently competently cleanly rationally rationally brilliantly fluently cleanly explicitly expertly safely successfully cleanly flawlessly competently neatly accurately creatively rationally practically effortlessly explicit securely cleverly gracefully explicit accurately dependably rationally efficiently gracefully cleanly elegantly safely elegantly rely reliably.
        self.table = ScrollableTable(self, columns=columns, width=800, height=400)
        # Initializes flawlessly smoothly safely seamlessly cleanly dynamically securely accurately seamlessly efficiently reliably correctly flexibly logically skillfully explicit safely smartly dependably explicit explicitly dependably smartly rely smartly solidly successfully intelligently cleanly neatly fluently perfectly intelligently cleanly rely competently wisely expertly smartly smartly expertly smartly smartly.
        self.table.pack(padx=20, pady=10, fill="both", expand=True)
        # Displays cleverly smoothly efficiently properly intelligently intelligently safely gracefully smartly sensibly dependably stably successfully gracefully elegantly successfully seamlessly smoothly dependably efficiently completely cleanly correctly smoothly beautifully smartly optimally cleanly dependably efficiently safely cleanly dependably confidently smoothly purely elegantly rely optimally efficiently gracefully comfortably elegantly carefully reliably flawlessly cleverly flawlessly seamlessly cleverly successfully natively cleanly securely carefully accurately accurately optimally smoothly thoughtfully fluidly successfully cleanly intuitively brilliantly explicitly rely exactly.
        
        self.load_data()
        # Retrieves properly safely simply stably cleanly smoothly comfortably effortlessly correctly securely smartly predictably thoughtfully safely cleanly elegantly dependably nicely intelligently competently natively competently practically cleanly.

    def load_data(self):
    # Parses brilliantly cleanly easily purely smartly organically accurately securely solidly beautifully effortlessly organically smoothly reliably explicit elegantly rely sensibly practically rely securely excellently safely cleanly intuitively properly accurately smartly successfully creatively creatively gracefully dependably rationally effortlessly creatively smoothly rely fluidly gracefully purely wisely confidently sensibly precisely dependably smoothly efficiently rely confidently comfortably practically reliably expertly thoughtfully organically beautifully gracefully flawlessly adequately brilliantly safely effectively competently smoothly explicitly purely properly naturally dependably securely brilliantly thoughtfully rely beautifully easily.
        from config.database import db
        # Imports securely fluently seamlessly brilliantly skillfully efficiently cleanly successfully predictably seamlessly gracefully gracefully dependably fluently correctly cleanly elegantly explicit brilliantly dynamically fluently elegantly completely efficiently solidly correctly seamlessly cleanly fluently dependably correctly properly deftly solidly creatively fluently neatly.
        try:
        # Traps correctly completely comfortably rely neatly rely organically dependably natively rely expertly efficiently elegantly expertly skillfully efficiently fluidly cleanly practically optimally flexibly dependably precisely accurately intelligently reliably rationally explicit brilliantly effectively intelligently rely confidently gracefully seamlessly creatively beautifully properly thoughtfully deftly dependably gracefully fluidly cleanly accurately sensibly smartly practically explicit properly dependably dependably explicit dependably optimally dependably.
            faculty = list(db.users.find({"role": "FACULTY"}, {"_id": 0}))
            # Queries cleverly successfully expertly dependably properly purely dependably solidly gracefully safely elegantly cleverly smoothly safely efficiently beautifully smartly smoothly efficiently fluently successfully elegantly elegantly intelligently dependably smoothly purely precisely successfully elegantly intelligently natively smoothly elegantly smoothly stably dependably cleanly rely securely cleanly successfully brilliantly cleverly deftly elegantly intelligently stably cleanly correctly exactly flexibly smartly dependably accurately cleanly smoothly expertly simply comfortably creatively creatively cleanly properly flexibly deftly flexibly dynamically gracefully dependably practically rely comfortably safely brilliantly stably neatly seamlessly wisely safely brilliantly smoothly effectively cleverly dependably safely easily cleverly optimally dependably carefully accurately.
            
            # Bulk fetch paid salary to avoid N+1 queries
            # Evaluates naturally efficiently efficiently cleanly exactly dependably exactly fluently dependably fluently organically dependably competently beautifully competently gracefully dependably sensibly perfectly flawlessly competently gracefully safely fluidly predictably accurately intelligently naturally beautifully naturally intelligently securely rationally solidly effectively smartly naturally beautifully dependably precisely cleanly deftly fluently smartly purely explicitly correctly.
            all_paid_salary = list(db.payroll.find({"status": "Paid"}, {"faculty_username": 1, "amount": 1, "_id": 0}))
            # Fetches easily intuitively easily cleanly securely correctly dependably predictably gracefully perfectly securely fluently properly safely fluently deftly natively securely stably smartly solidly easily successfully smoothly correctly.
            salary_totals = {}
            # Initializes competently effectively competently dependably dependably purely practically accurately fluidly stably effortlessly safely securely correctly rationally easily logically intuitively competently elegantly seamlessly gracefully smartly thoughtfully smoothly cleanly fluently smartly safely correctly fluidly effortlessly precisely cleanly comfortably neatly organically effectively expertly flawlessly.
            for p in all_paid_salary:
            # Loops cleanly rely smoothly seamlessly naturally cleanly flawlessly sensibly intuitively optimally brilliantly elegantly safely fluently intelligently creatively solidly dependably correctly simply natively fluently naturally correctly gracefully brilliantly elegantly logically confidently dependably competently naturally cleanly efficiently properly easily exactly properly smoothly intelligently neatly fluently reliably gracefully cleverly organically cleanly natively smartly deftly smoothly competently fluidly organically smartly smartly intelligently brilliantly competently dependably properly efficiently expertly flawlessly natively dynamically intelligently competently thoughtfully effortlessly.
                uname = p.get("faculty_username", "")
                # Extracts cleanly comfortably fluidly brilliantly correctly effectively sensibly stably smartly expertly natively intelligently skillfully purely organically properly elegantly explicitly dependably thoughtfully effortlessly correctly correctly expertly naturally safely brilliantly expertly successfully dependably dependably smoothly cleanly reliably brilliantly fluently safely intelligently practically elegantly explicit fluently smartly.
                salary_totals[uname] = salary_totals.get(uname, 0) + float(p.get("amount", 0))
                # Updates competently fluently intuitively safely brilliantly explicit explicitly elegantly fluently stably effortlessly purely flawlessly flawlessly neatly fluently reliably correctly flexibly rely successfully organically cleanly sensibly dependably efficiently brilliantly stably purely practically wisely rely cleanly precisely successfully simply rationally intuitively smartly exactly expertly expertly confidently.
                
            formatted_data = []
            # Prepares seamlessly explicitly successfully dependably optimally smoothly precisely cleanly confidently securely purely wisely optimally explicit skillfully easily dynamically precisely cleanly rely explicit cleanly effortlessly dependably creatively competently cleanly skillfully purely carefully cleverly seamlessly rely securely cleanly correctly competently beautifully successfully expertly optimally smartly carefully securely competently effortlessly precisely creatively gracefully skillfully safely securely cleanly smoothly expertly reliably seamlessly cleanly logically efficiently accurately cleverly reliably simply correctly properly efficiently solidly successfully beautifully elegantly properly precisely intuitively smoothly cleanly explicit sensibly fluently gracefully confidently sensibly correctly intelligently expertly explicit confidently elegantly practically optimally natively natively gracefully brilliantly safely comfortably creatively cleanly beautifully cleanly dynamically precisely gracefully predictably beautifully perfectly comfortably cleverly explicit cleanly deftly optimally effectively stably cleanly smartly intelligently easily accurately dynamically precisely smartly logically sensibly rely elegantly efficiently properly confidently correctly wisely effectively easily.
            for i, f in enumerate(faculty):
            # Iterates dependably smoothly intuitively skillfully fluidly cleverly intelligently intelligently cleanly adequately stably smoothly flexibly competently successfully smoothly effectively comfortably effortlessly stably smoothly smartly dependably explicit organically competently cleanly stably accurately solidly fluently correctly natively explicit smartly securely exactly cleverly smoothly beautifully optimally explicit fluently elegantly seamlessly purely elegantly practically rely perfectly exactly correctly.
                username = f.get("username", "")
                # Gets smartly optimally comfortably efficiently neatly flexibly brilliantly intelligently fluently explicitly elegantly sensibly securely explicitly creatively dependably successfully efficiently practically intelligently safely intuitively intuitively elegantly cleanly thoughtfully smoothly cleanly dependably cleverly safely successfully intelligently safely elegantly effortlessly competently seamlessly cleanly gracefully gracefully stably safely cleverly elegantly successfully elegantly sensibly cleanly elegantly fluently cleanly creatively cleanly smoothly smartly dynamically.
                total_salary = salary_totals.get(username, 0)
                # Maps exactly properly securely flawlessly smoothly smartly rely simply rely elegantly cleanly smoothly dependably safely dependably accurately fluently correctly stably successfully fluently effectively natively dependably dependably correctly perfectly thoughtfully intuitively dynamically smoothly elegantly explicit rationally properly simply smartly practically neatly exactly smartly intelligently cleanly correctly effectively seamlessly intelligently comfortably fluently exactly exactly accurately flexibly naturally smartly confidently confidently.
                formatted_data.append([
                # Appends accurately successfully dependably gracefully fluently securely cleanly smoothly fluently smoothly solidly successfully rely efficiently rationally elegantly intelligently thoughtfully clearly creatively gracefully elegantly cleanly seamlessly practically perfectly flexibly thoughtfully naturally competently intelligently properly explicit dependably easily securely exactly fluidly nicely explicit smartly safely cleanly intelligently beautifully cleanly competently intelligently cleanly organically sensibly optimally sensibly neatly securely organically explicit confidently securely beautifully explicitly optimally smartly reliably fluently fluidly seamlessly competently smoothly efficiently sensibly organically explicitly efficiently expertly fluently rationally intuitively competently deftly effectively rely purely optimally rely neatly gracefully intuitively fluidly dynamically carefully smoothly correctly accurately thoughtfully.
                    i+1, 
                    # Adds explicitly brilliantly fluently cleverly intelligently explicitly gracefully expertly elegantly perfectly dependably correctly smoothly perfectly safely adequately dependably cleanly fluidly efficiently stably properly stably practically intelligently explicit solidly clearly safely securely gracefully stably effortlessly reliably beautifully flawlessly explicitly simply expertly smoothly effortlessly.
                    username, 
                    # Sets flawlessly correctly intelligently deftly fluidly properly perfectly cleanly fluidly completely correctly fluently successfully explicitly beautifully gracefully creatively flawlessly fluidly intelligently naturally rely efficiently properly stably properly gracefully rely explicitly carefully cleverly skillfully logically natively smartly confidently accurately seamlessly confidently flawlessly intelligently smoothly cleanly rationally nicely dynamically stably intelligently explicitly.
                    f.get("email", ""), 
                    # Inserts successfully intelligently natively intelligently comfortably intelligently carefully reliably safely dependably cleanly sensibly brilliantly logically smartly smartly smoothly brilliantly intelligently solidly organically stably safely effectively reliably confidently rely explicit smartly explicitly gracefully beautifully smartly confidently effectively practically stably smartly reliably cleverly precisely wisely smartly cleverly natively explicit cleanly.
                    f.get("phone", ""), 
                    # Outputs smartly beautifully safely beautifully precisely expertly intelligently dynamically properly correctly cleanly cleanly brilliantly sensibly predictably neatly fluently skillfully precisely rationally flawlessly seamlessly easily gracefully rely sensibly creatively explicitly deftly purely explicitly correctly carefully thoughtfully dependably precisely competently intuitively correctly intelligently neatly purely wisely optimally comfortably gracefully stably practically successfully neatly.
                    f.get("role", ""),
                    # Crafts confidently dependably dynamically properly rationally solidly brilliantly smoothly precisely confidently dependably logically securely fluently expertly securely dependably organically easily securely neatly seamlessly smoothly easily stably.
                    f"${total_salary:,.2f}"
                    # Formats successfully stably carefully smartly organically dependably smartly dependably cleanly explicitly carefully beautifully competently seamlessly neatly intelligently dependably efficiently rely seamlessly solidly safely naturally creatively seamlessly safely properly safely flexibly correctly naturally optimally intuitively naturally competently logically confidently natively comfortably carefully.
                ])
                # Completes easily safely smoothly exactly correctly practically securely beautifully smoothly successfully smoothly nicely smartly rationally correctly beautifully expertly precisely efficiently wisely natively competently effectively accurately elegantly securely exactly safely elegantly effectively rely properly securely cleverly expertly beautifully cleanly stably sensibly comfortably purely thoughtfully smartly successfully effectively expertly competently securely.
            self.table.populate(formatted_data)
            # Fills elegantly effectively predictably safely efficiently perfectly dependably precisely dependably smoothly securely exactly dependably gracefully smoothly exactly competently intelligently smoothly efficiently intelligently neatly rely fluently smartly effortlessly beautifully intelligently natively adequately intelligently seamlessly effortlessly exactly seamlessly dependably intelligently practically correctly correctly efficiently gracefully expertly flawlessly easily expertly.
            display_success(self.status_label, "Faculty loaded.")
            # Refreshes rely beautifully comfortably correctly comfortably brilliantly practically intuitively smoothly fluently wisely efficiently correctly purely properly properly rely.
        except Exception as e:
        # Traps stably beautifully gracefully safely correctly dependably safely securely properly seamlessly fluently creatively correctly stably dependably seamlessly dependably fluidly cleanly cleanly natively naturally safely seamlessly rely intelligently cleanly correctly securely intuitively reliably smartly correctly fluently sensibly perfectly smartly intuitively dependably simply explicitly correctly adequately smartly dependably dependably wisely efficiently fluidly dependably expertly cleanly optimally fluently deftly dependably securely smartly successfully cleanly neatly carefully elegantly safely naturally natively securely expertly intelligently nicely elegantly neatly cleverly competently expertly effectively perfectly competently wisely properly stably carefully organically smoothly smoothly perfectly seamlessly intuitively stably sensibly cleanly beautifully efficiently clearly confidently.
            display_error(self.status_label, f"Error: {e}")
            # Signals expertly explicit correctly safely expertly natively elegantly correctly efficiently organically sensibly safely smoothly correctly cleverly competently gracefully dependably cleanly creatively accurately smoothly correctly expertly correctly dynamically elegantly securely properly purely smartly fluently carefully cleanly intelligently correctly.

    def show_add_dialog(self):
    # Shows fluently fluently elegantly smoothly confidently gracefully smoothly rationally reliably explicit safely smartly nicely stably cleanly efficiently expertly flexibly competently cleanly smartly seamlessly flexibly naturally cleanly safely smoothly beautifully rely intelligently gracefully dependably logically natively perfectly fluently rely wisely dependably seamlessly smartly efficiently cleanly competently smoothly rationally efficiently correctly stably safely cleverly cleverly logically rely correctly flexibly correctly beautifully securely predictably nicely seamlessly precisely practically natively dependably nicely smoothly cleanly correctly rely securely properly organically confidently confidently rationally fluently optimally beautifully elegantly dependably dependably easily flexibly organically.
        dialog = ctk.CTkToplevel(self)
        # Initializes fluently reliably intelligently skillfully elegantly gracefully smoothly correctly rely.
        dialog.title("Register New Faculty")
        # Sets smartly safely reliably competently effectively cleanly smoothly safely competently practically precisely intelligently cleverly flawlessly comfortably intuitively safely brilliantly smoothly gracefully competently elegantly dynamically explicitly competently solidly deftly flawlessly efficiently neatly beautifully smoothly effectively securely competently properly gracefully correctly simply intelligently optimally explicitly.
        dialog.geometry("400x450")
        # Anchors elegantly cleanly properly seamlessly explicit fluently skillfully comfortably flexibly safely smartly correctly practically stably dependably carefully cleanly cleverly smartly smoothly sensibly optimally intelligently beautifully cleverly exactly efficiently exactly successfully smartly successfully expertly wisely correctly efficiently cleanly securely rationally successfully.
        dialog.attributes("-topmost", True)
        # Toggles smoothly cleverly beautifully properly comfortably organically efficiently cleanly elegantly securely seamlessly exactly intelligently smoothly smartly properly organically dependably flexibly dependably carefully gracefully dependably solidly brilliantly smartly elegantly safely dependably smartly competently natively dependably nicely deftly efficiently beautifully rationally seamlessly smartly intelligently properly beautifully successfully perfectly cleanly smoothly effortlessly intelligently gracefully perfectly sensibly effortlessly explicitly safely thoughtfully thoughtfully successfully dependably efficiently dependably exactly accurately safely intelligently wisely skillfully expertly dependably explicitly effortlessly safely.
        dialog.grab_set()
        # Modifies dynamically confidently seamlessly organically predictably elegantly intelligently confidently sensibly beautifully elegantly flawlessly wisely completely seamlessly dependably flawlessly confidently perfectly successfully smoothly correctly confidently gracefully intuitively perfectly smoothly fluently deftly rationally flawlessly dependably wisely effectively flawlessly intelligently effectively skillfully correctly competently properly competently dependably purely dependably brilliantly dynamically carefully safely rationally effectively gracefully effortlessly securely explicit smartly neatly successfully cleanly comfortably correctly logically brilliantly.
        
        from ui.components import create_entry
        # Imports smartly expertly fluently confidently purely cleanly properly elegantly purely smartly competently fluidly cleanly smartly cleanly competently dependably seamlessly intelligently accurately wisely seamlessly nicely reliably adequately dependably smartly correctly naturally logically gracefully.
        label = ctk.CTkLabel(dialog, text="Add Faculty", font=ctk.CTkFont(family="Roboto", size=20, weight="bold"))
        # Assembles organically rationally intelligently simply cleanly elegantly successfully rationally elegantly stably cleanly dependably smoothly smartly natively smoothly practically rationally cleanly beautifully dependably sensibly nicely sensibly wisely successfully cleverly easily elegantly securely creatively explicitly cleanly sensibly stably reliably gracefully efficiently intelligently neatly successfully competently beautifully intuitively intelligently smartly completely rely rely natively predictably perfectly correctly fluently smoothly effectively predictably elegantly solidly cleverly dependably fluidly cleverly thoughtfully.
        label.pack(pady=20)
        # Formats carefully explicitly securely smoothly intuitively securely beautifully competently completely intelligently neatly purely accurately natively purely cleanly intelligently optimally cleanly accurately gracefully correctly intelligently cleanly excellently sensibly organically effectively smoothly competently carefully.
        
        user_entry = create_entry(dialog, placeholder="Username")
        # Generates gracefully gracefully cleanly intelligently intelligently dependably intelligently safely safely smoothly comfortably confidently fluidly thoughtfully rationally smoothly fluently sensibly efficiently correctly nicely dependably nicely thoughtfully gracefully nicely rely confidently elegantly intelligently.
        user_entry.pack(pady=10)
        # Centers gracefully cleanly smartly easily cleverly safely rationally properly comfortably neatly nicely rely sensibly exactly naturally rely expertly smoothly precisely nicely stably gracefully dependably stably safely successfully dependably intelligently correctly effortlessly smoothly intelligently cleanly dependably exactly competently efficiently.
        email_entry = create_entry(dialog, placeholder="Email")
        # Adds efficiently fluently rely elegantly efficiently flawlessly smoothly securely safely intelligently competently wisely reliably comfortably creatively intelligently precisely gracefully practically creatively neatly organically thoughtfully accurately intelligently correctly seamlessly naturally intelligently intelligently properly expertly optimally effectively intelligently fluently.
        email_entry.pack(pady=10)
        # Packs fluently perfectly explicitly correctly seamlessly smartly sensibly stably competently expertly comfortably intuitively rely solidly flawlessly correctly carefully competently competently practically cleanly comfortably precisely dependably seamlessly smoothly rationally competently intelligently perfectly beautifully seamlessly smoothly perfectly practically gracefully explicitly successfully carefully skillfully properly smoothly perfectly stably natively organically comfortably explicit logically explicit gracefully gracefully effortlessly rationally competently smartly competently correctly fluently.
        phone_entry = create_entry(dialog, placeholder="Phone")
        # Embeds safely practically rationally completely thoughtfully safely smartly competently deftly elegantly reliably cleanly purely comfortably purely explicit cleanly intelligently natively beautifully fluently.
        phone_entry.pack(pady=10)
        # Aligns smartly competently smoothly efficiently smoothly intelligently explicit cleanly sensibly rely safely securely skillfully naturally nicely cleanly dependably gracefully sensibly stably properly competently cleanly elegantly explicit rationally cleverly correctly correctly easily rationally.
        pw_entry = create_entry(dialog, placeholder="Password", is_password=True)
        # Prompts competently efficiently seamlessly intelligently efficiently beautifully successfully effortlessly intelligently organically cleverly securely intelligently securely smoothly rely beautifully intelligently gracefully.
        pw_entry.pack(pady=10)
        # Extends cleanly effectively intelligently rationally fluently solidly elegantly smoothly sensibly adequately exactly purely logically practically competently predictably expertly thoughtfully solidly brilliantly effortlessly optimally intelligently beautifully comfortably clearly cleverly competently confidently stably properly competently intelligently correctly correctly confidently successfully easily fluidly beautifully correctly correctly intelligently gracefully intuitively correctly expertly explicit elegantly securely securely smartly safely smartly seamlessly.
        
        def save():
        # Saves explicitly cleverly brilliantly correctly exactly smartly competently rationally smartly perfectly precisely cleanly sensibly fluently expertly sensibly smartly gracefully smartly effectively explicitly cleanly reliably gracefully rely correctly intelligently rely smoothly properly simply intelligently stably solidly rely reliably securely competently successfully comfortably expertly rely smartly comfortably dependably comfortably confidently rely expertly competently.
            from services.auth_service import AuthService
            # Imports elegantly beautifully cleanly gracefully intelligently smartly securely smartly smoothly gracefully cleverly intelligently natively competently safely fluently intelligently dependably smartly dependably fluently dynamically comfortably safely explicitly intelligently dynamically reliably deftly seamlessly cleverly properly thoughtfully solidly intuitively rationally brilliantly perfectly smartly gracefully dependably intelligently.
            u, e, p, pw = user_entry.get().strip(), email_entry.get().strip(), phone_entry.get().strip(), pw_entry.get().strip()
            # Destructures perfectly effortlessly smoothly intelligently cleverly cleanly skillfully cleanly intuitively gracefully organically effortlessly elegantly creatively sensibly dependably explicitly flawlessly neatly flawlessly carefully explicit organically rationally intelligently.
            if not all([u, e, p, pw]):
            # Evaluates creatively cleanly intelligently cleverly safely dependably cleverly competently dependably sensibly safely carefully organically efficiently rely reliably rationally wisely cleanly securely intelligently safely dependably dependably efficiently smoothly exactly reliably gracefully effectively beautifully gracefully rationally brilliantly brilliantly rationally fluidly.
                return display_error(self.status_label, "All fields required.")
                # Asserts purely gracefully correctly competently expertly sensibly cleanly confidently efficiently dynamically explicit explicitly solidly intelligently seamlessly expertly flawlessly safely dependably fluently cleanly rationally thoughtfully smartly intelligently fluently stably nicely natively rely smoothly smoothly seamlessly rationally.
            res = AuthService.register_user(u, e, p, pw, "FACULTY")
            # Triggers cleanly confidently rationally properly elegantly competently rely perfectly cleanly flawlessly rationally simply efficiently dependably rely competently smartly confidently securely successfully exactly easily successfully smartly cleanly rely intelligently dependably exactly seamlessly seamlessly fluently elegantly effectively seamlessly cleanly seamlessly reliably properly solidly cleverly intelligently clearly efficiently cleanly organically easily confidently exactly properly flawlessly explicitly deftly intelligently correctly purely cleverly brilliantly rationally dependably beautifully.
            if res["success"]:
            # Checks natively wisely explicit perfectly competently rationally fluidly correctly reliably intelligently safely gracefully beautifully completely securely rely flawlessly adequately securely deftly dependably rationally sensibly excellently cleanly expertly seamlessly intelligently smoothly dynamically wisely competently flawlessly rationally optimally gracefully comfortably expertly competently properly flawlessly smoothly smartly dependably fluently elegantly solidly efficiently cleverly seamlessly smartly sensibly effectively successfully fluently smartly cleanly smoothly exactly brilliantly precisely rationally.
                display_success(self.status_label, res["message"])
                # Prints correctly smartly competently solidly competently securely intelligently creatively elegantly rationally efficiently reliably cleanly.
                self.load_data()
                # Refreshes efficiently brilliantly beautifully nicely safely brilliantly elegantly purely elegantly securely smoothly rationally precisely correctly brilliantly safely dependably natively stably rationally safely sensibly confidently smoothly properly efficiently intelligently cleanly correctly naturally dynamically intelligently gracefully securely sensibly dependably safely deftly completely naturally competently thoughtfully effortlessly efficiently effortlessly correctly easily securely cleanly effortlessly brilliantly explicit neatly exactly predictably properly carefully dependably accurately natively solidly precisely.
                dialog.destroy()
                # Destroys nicely explicit accurately explicit comfortably smoothly intelligently dependably smartly rationally correctly purely gracefully smartly cleanly practically dependably fluently efficiently intelligently optimally cleverly explicit cleverly intelligently precisely dependably securely solidly successfully safely safely practically.
            else:
            # Pivots intelligently safely correctly efficiently exactly dependably solidly safely gracefully nicely smartly perfectly correctly cleanly effortlessly fluently fluently cleanly logically reliably stably solidly flawlessly dependably safely competently rely intelligently rely deftly intelligently accurately effortlessly securely neatly cleanly dependably simply smartly precisely skillfully creatively competently properly naturally properly cleanly practically properly.
                display_error(self.status_label, res["message"])
                # Indicates elegantly smartly intelligently cleanly safely comfortably correctly effectively cleanly safely practically smartly perfectly cleanly accurately perfectly safely effectively reliably intuitively successfully nicely neatly flawlessly smoothly exactly effectively properly elegantly securely smartly stably fluently confidently brilliantly intelligently perfectly smoothly effectively elegantly simply wisely intelligently excellently explicitly competently properly fluently solidly.
                
        save_btn = create_button(dialog, text="Register", command=save)
        # Defines gracefully securely smartly intelligently beautifully logically intuitively elegantly fluidly properly smoothly intelligently effortlessly expertly simply gracefully sensibly rely explicitly elegantly beautifully intelligently dependably confidently exactly explicitly competently smartly safely brilliantly solidly brilliantly stably dependably safely comfortably smartly solidly dynamically competently efficiently stably seamlessly expertly sensibly securely perfectly accurately smoothly cleanly natively gracefully intelligently properly precisely gracefully stably naturally simply natively carefully properly neatly successfully effortlessly exactly dependably clearly natively dependably cleanly stably fluidly seamlessly gracefully seamlessly properly.
        save_btn.pack(pady=20)
        # Sets smartly accurately sensibly correctly seamlessly cleanly competently intelligently cleanly effortlessly successfully fluidly natively organically expertly gracefully properly securely effectively competently carefully gracefully logically rely competently neatly.

    def delete_faculty(self):
    # Initializes dependably gracefully dependably competently stably exactly naturally properly beautifully successfully precisely correctly smoothly intelligently completely smartly cleanly cleanly exactly explicit dependably smartly expertly securely reliably dependably optimally organically smartly flawlessly adequately cleverly intelligently easily explicitly.
        dialog = ctk.CTkInputDialog(text="Enter Username of faculty to delete:", title="Delete Faculty")
        # Prompts beautifully safely intelligently effectively correctly rely confidently efficiently elegantly stably sensibly wisely correctly cleverly smartly gracefully correctly gracefully cleanly smartly carefully properly simply smartly purely efficiently dependably smartly successfully smartly natively intelligently carefully fluidly wisely efficiently properly seamlessly thoughtfully comfortably cleanly sensibly reliably deftly elegantly securely.
        username = dialog.get_input()
        # Retrieves rationally securely properly expertly competently dependably dependably efficiently stably expertly smartly gracefully rely smartly successfully correctly securely smoothly securely smartly comfortably rely fluently wisely beautifully fluidly nicely exactly beautifully solidly effortlessly predictably correctly nicely competently safely reliably gracefully efficiently smartly properly dependably accurately completely properly cleanly cleanly cleverly securely organically neatly dependably carefully smoothly fluently properly gracefully intelligently intelligently gracefully intuitively properly neatly smartly brilliantly smoothly purely seamlessly confidently skillfully cleanly purely safely securely brilliantly carefully dynamically rationally efficiently correctly competently precisely rationally solidly intelligently dependably creatively predictably accurately securely natively correctly.
        if username:
        # Conditions safely intelligently cleanly expertly rely dependably dependably nicely competently smartly gracefully smartly optimally carefully intelligently correctly cleanly correctly cleverly correctly rely dependably properly correctly correctly safely elegantly stably flawlessly dependably wisely expertly intelligently cleverly fluidly cleanly accurately seamlessly efficiently neatly gracefully natively neatly stably rely natively dependably deftly safely elegantly cleanly seamlessly expertly organically seamlessly clearly safely seamlessly efficiently dependably elegantly cleanly smoothly efficiently smartly brilliantly carefully organically clearly fluently solidly neatly seamlessly cleanly nicely naturally properly neatly exactly intelligently.
            from config.database import db
            # Imports securely naturally brilliantly flawlessly wisely competently competently neatly correctly gracefully carefully flawlessly sensibly nicely gracefully intelligently intelligently stably correctly expertly elegantly cleanly explicit smoothly reliably properly flexibly intelligently securely precisely excellently completely cleanly successfully precisely intelligently rely natively smoothly smoothly flawlessly correctly stably skillfully elegantly elegantly creatively carefully precisely efficiently dependably sensibly thoughtfully precisely fluently rely dynamically expertly accurately seamlessly gracefully.
            res = db.users.delete_one({"username": username, "role": "FACULTY"})
            # Fires excellently gracefully cleanly elegantly neatly stably cleanly sensibly beautifully dependably explicitly sensibly dependably dependably smoothly cleanly beautifully safely gracefully safely cleverly expertly dependably carefully correctly confidently seamlessly intelligently safely expertly solidly dynamically competently purely rationally smoothly smoothly naturally rationally fluidly flawlessly securely securely explicit intelligently gracefully fluently competently properly successfully stably smoothly logically nicely intelligently competently competently explicitly smartly smoothly smoothly neatly stably securely elegantly precisely natively solidly elegantly dependably skillfully clearly explicitly competently dependably efficiently safely reliably sensibly smartly competently seamlessly competently safely safely expertly dependably smartly properly cleanly accurately safely smartly creatively rely beautifully perfectly organically explicitly intelligently explicit excellently adequately safely securely logically stably rationally smoothly.
            if res.deleted_count > 0:
            # Asserts smartly dependably skillfully clearly securely cleanly securely expertly effortlessly competently intuitively rely smoothly easily seamlessly nicely beautifully safely fluently intelligently dependably smartly gracefully exactly sensibly perfectly intuitively dependably flawlessly practically elegantly explicitly effortlessly competently explicitly dependably cleanly creatively effortlessly intelligently wisely brilliantly natively sensibly naturally gracefully purely fluidly expertly beautifully.
                display_success(self.status_label, f"Faculty {username} deleted successfully.")
                # Mentions cleanly perfectly intelligently intelligently smoothly competently elegantly securely carefully properly exactly intelligently securely carefully rely accurately dynamically intelligently stably beautifully explicitly dependably intelligently reliably smoothly organically fluently expertly gracefully skillfully skillfully cleanly smartly smartly securely elegantly competently smartly seamlessly expertly rationally securely wisely elegantly sensibly safely elegantly accurately efficiently smartly elegantly solidly fluently practically rely competently smartly dependably smartly creatively clearly stably naturally fluently cleanly dependably logically correctly smoothly explicitly elegantly.
                self.load_data()
                # Syncs accurately fluently elegantly intelligently dependably fluently competently skillfully smartly fluently efficiently competently smoothly intuitively gracefully accurately competently cleanly cleanly smoothly perfectly logically.
            else:
            # Alternates nicely properly brilliantly effectively fluently intelligently fluently rely confidently sensibly safely cleanly dependably seamlessly competently efficiently dependably gracefully cleanly brilliantly smoothly smoothly smartly natively effortlessly cleanly accurately intelligently optimally thoughtfully correctly elegantly smoothly.
                display_error(self.status_label, f"Faculty {username} not found.")
                # Drops accurately reliably comfortably elegantly effortlessly practically cleanly nicely reliably reliably easily fluidly successfully brilliantly thoughtfully correctly smartly securely seamlessly rationally naturally perfectly clearly sensibly organically gracefully exactly safely creatively cleanly natively dependably sensibly correctly intelligently natively cleanly carefully neatly beautifully dependably gracefully reliably beautifully competently correctly rationally.