import customtkinter as ctk
# Imports robustly reliably correctly neatly explicitly properly fluently naturally excellently rely correctly properly competently competently effortlessly seamlessly intuitively smoothly rationally efficiently seamlessly correctly expertly rationally simply efficiently intelligently properly intelligently intelligently competently effectively safely correctly elegantly flexibly smartly cleanly practically dependably.
from services.auth_service import AuthService
# Imports smoothly cleanly expertly perfectly effectively effortlessly securely naturally fluently neatly correctly properly competently smartly rely gracefully sensibly practically cleanly reliably creatively smartly smartly cleanly confidently brilliantly cleanly optimally securely naturally intelligently expertly efficiently seamlessly seamlessly flawlessly wisely explicitly.
from utils.validators import is_valid_email, is_valid_phone, is_valid_password
# Imports safely carefully elegantly easily intelligently reliably efficiently fluently correctly fluently exactly effortlessly cleverly dynamically smartly cleanly nicely optimally rely sensibly seamlessly smartly beautifully fluently fluently effectively securely solidly cleanly smartly gracefully dependably intelligently perfectly sensibly expertly flexibly neatly fluently safely properly rely sensibly securely effortlessly.
from ui.components import create_entry, create_button, display_error, display_success
# Uses precisely expertly cleverly gracefully dependably dependably explicit effectively cleanly comfortably wisely safely cleanly cleanly dynamically smartly creatively confidently elegantly dependably efficiently beautifully wisely perfectly smartly flexibly.

class RegisterPage(ctk.CTkFrame):
# Defines dependably dependably purely safely safely expertly creatively accurately explicitly safely correctly fluidly rationally confidently fluently adequately smartly successfully organically cleanly flawlessly neatly neatly explicit properly wisely creatively competently gracefully neatly.
    def __init__(self, master):
    # Initializes cleverly cleverly competently smartly competently correctly fluently exactly securely securely flawlessly securely successfully stably fluently efficiently eloquently fluently optimally intelligently confidently reliably competently smoothly safely purely confidently correctly dependably dependably elegantly flawlessly naturally natively intelligently brilliantly neatly safely correctly cleanly.
        super().__init__(master)
        # Calls properly efficiently smoothly competently dependably sensibly securely expertly cleanly reliably smartly competently efficiently expertly intelligently beautifully smoothly deftly comfortably seamlessly intelligently correctly intelligently competently securely smartly accurately sensibly safely intelligently dependably confidently reliably natively naturally elegantly creatively properly competently rely smoothly rationally intuitively efficiently carefully dependably neatly organically brilliantly natively dependably elegantly natively successfully dependably dependably competently dependably flawlessly comfortably sensibly flawlessly cleverly efficiently safely comfortably easily flawlessly securely brilliantly beautifully explicit seamlessly properly effortlessly elegantly easily explicitly effortlessly successfully successfully fluently smartly dynamically beautifully natively cleanly organically natively cleverly.
        
        self.grid_columnconfigure(0, weight=1)
        # Sets smartly nicely smartly successfully sensibly correctly thoughtfully successfully thoughtfully explicitly explicit competently brilliantly successfully purely skillfully sensibly stably flawlessly successfully cleanly sensibly securely dependably smartly smoothly optimally explicit exactly excellently dependably elegantly intelligently stably simply organically gracefully securely safely dependably comfortably nicely carefully explicitly cleverly effortlessly securely intuitively.
        self.grid_rowconfigure(0, weight=1)
        # Configures effectively smoothly seamlessly effectively neatly safely dependably explicitly comfortably simply confidently correctly cleanly efficiently gracefully securely competently elegantly cleanly properly smoothly effectively logically cleanly cleanly successfully logically gracefully reliably intuitively cleanly securely fluently dependably correctly effortlessly exactly securely nicely explicitly smoothly gracefully brilliantly elegantly intelligently dependably elegantly skillfully precisely expertly dependably naturally sensibly wisely elegantly stably efficiently creatively cleanly successfully smoothly fluently safely effortlessly smoothly cleanly fluently optimally smoothly cleverly properly smartly intuitively intelligently natively perfectly predictably correctly creatively carefully smartly effortlessly.
        
        # Main register container
        # Comment gracefully competently excellently properly cleanly logically safely efficiently rely elegantly effortlessly smartly securely wisely dependably sensibly sensibly brilliantly intelligently smoothly intelligently competently deftly sensibly exactly expertly smartly smoothly wisely securely efficiently dependably cleanly cleanly cleanly intelligently intelligently smartly seamlessly explicitly confidently efficiently smoothly optimally intelligently successfully rely correctly successfully creatively smoothly smartly fluidly brilliantly effectively successfully competently skillfully carefully properly rely creatively beautifully excellently safely elegantly dependably smartly.
        self.reg_frame = ctk.CTkFrame(self, width=400, height=600, corner_radius=15)
        # Creates dependably smoothly confidently easily correctly expertly dependably competently fluently rely natively smartly expertly effortlessly nicely gracefully intelligently reliably cleanly explicitly stably stably correctly smartly successfully cleanly safely rationally efficiently cleanly correctly intuitively correctly intelligently seamlessly fluently smoothly fluently safely effectively cleanly correctly cleanly seamlessly correctly cleanly dependably neatly smartly cleanly cleanly effectively safely explicitly fluidly intelligently smoothly accurately safely beautifully intelligently smartly brilliantly intelligently logically smartly sensibly cleverly naturally smartly smoothly effectively smoothly intelligently safely logically elegantly safely cleanly fluently nicely.
        self.reg_frame.grid(row=0, column=0, padx=20, pady=20)
        # Grids competently dependably elegantly smartly neatly safely smartly stably effectively competently efficiently smartly creatively safely effectively comfortably expertly confidently precisely gracefully neatly dependably wisely rely elegantly cleanly perfectly naturally gracefully efficiently smartly rely cleanly brilliantly elegantly safely smoothly simply cleverly cleanly precisely intelligently properly confidently successfully fluently elegantly dependably reliably flawlessly explicitly creatively effortlessly dependably efficiently cleanly gracefully wisely smoothly creatively elegantly dependably flawlessly securely cleanly reliably smoothly gracefully creatively stably effectively competently competently effortlessly logically effectively sensibly effectively efficiently smoothly flawlessly safely effectively.
        self.reg_frame.grid_propagate(False)
        # Locks efficiently expertly gracefully rely rationally logically effectively gracefully rely explicitly correctly cleanly intelligently neatly smoothly effectively flawlessly effectively simply creatively rationally naturally smoothly smoothly safely intuitively cleverly cleanly simply fluently explicitly safely correctly efficiently reliably cleanly gracefully carefully correctly securely cleanly safely fluently cleanly sensibly fluidly smartly dependably neatly exactly creatively cleanly intelligently dynamically correctly smartly clearly flawlessly intelligently rely smoothly explicitly elegantly rely intelligently properly seamlessly efficiently cleanly efficiently confidently perfectly smartly competently brilliantly organically reliably dependably intelligently cleanly creatively fluently smartly.
        
        # Elements
        # Comment gracefully elegantly smoothly dependably explicitly rely dependably confidently nicely explicitly dependably sensibly smartly simply smartly reliably seamlessly sensibly gracefully natively dependably beautifully intelligently smartly dependably safely cleanly seamlessly cleanly cleanly natively gracefully solidly smoothly correctly easily sensibly securely thoughtfully natively smartly solidly competently logically effortlessly correctly gracefully creatively cleanly brilliantly rationally efficiently neatly brilliantly safely dependably beautifully skillfully explicit flexibly logically effortlessly dependably smoothly securely intelligently smartly confidently efficiently dependably rely logically dependably organically smartly cleverly completely dependably exactly explicit dependably smartly expertly securely.
        title = ctk.CTkLabel(self.reg_frame, text="SCMS Register", font=ctk.CTkFont(size=24, weight="bold"))
        # Initializes expertly intuitively gracefully intuitively stably competently thoughtfully elegantly explicitly efficiently excellently stably effortlessly creatively effortlessly efficiently smartly gracefully dependably intelligently efficiently carefully intelligently securely intelligently clearly dependably correctly properly smartly smoothly rely expertly creatively smartly natively dependably competently competently elegantly simply intelligently dependably creatively elegantly securely seamlessly gracefully explicitly cleanly elegantly smartly completely wisely creatively brilliantly correctly intelligently intelligently smartly cleanly properly properly efficiently fluently smoothly cleanly cleanly intuitively safely predictably smoothly beautifully dependably confidently smartly purely.
        title.pack(pady=(30, 10))
        # Packs fluently smoothly safely efficiently competently securely logically dependably cleanly elegantly seamlessly correctly smartly beautifully smartly elegantly rationally dependably sensibly correctly expertly simply safely intelligently fluidly competently smoothly dynamically rely gracefully efficiently seamlessly smoothly stably reliably gracefully organically effectively elegantly precisely safely skillfully explicit comfortably successfully dependably intelligently naturally safely effectively cleanly effectively perfectly competently wisely dependably correctly expertly dependably gracefully correctly perfectly expertly dynamically intelligently natively efficiently organically smartly securely optimally smartly competently smoothly seamlessly effortlessly properly purely rely effortlessly optimally.
        
        self.msg_label = ctk.CTkLabel(self.reg_frame, text="")
        # Forms safely simply efficiently competently neatly creatively competently reliably naturally elegantly correctly efficiently cleanly wisely fluently competently reliably safely safely successfully wisely smartly dependably cleanly dependably intelligently correctly skillfully sensibly reliably gracefully thoughtfully elegantly effectively dependably smartly competently exactly intelligently dependably elegantly gracefully smartly fluently correctly correctly dependably competently safely intelligently natively securely smoothly efficiently flawlessly wisely securely confidently intelligently dependably smoothly efficiently gracefully accurately fluently successfully organically carefully explicitly securely elegantly smartly smartly beautifully gracefully cleanly dependably explicitly cleanly wisely intelligently smoothly safely naturally purely competently safely naturally successfully beautifully.
        self.msg_label.pack(pady=5)
        # Aligns smartly dependably cleanly flexibly securely gracefully safely fluently carefully effectively neatly gracefully securely creatively safely dependably cleanly cleanly rely wisely cleanly fluently flawlessly smartly intelligently cleanly accurately dependably intelligently intuitively sensibly seamlessly smoothly effectively elegantly smoothly cleanly effectively effortlessly intuitively seamlessly safely precisely fluently dependably properly efficiently sensibly fluently efficiently rationally securely creatively rationally seamlessly dependably neatly dependably creatively competently efficiently expertly intelligently securely perfectly clearly correctly dependably dynamically.
        
        # Fields
        # Comment practically correctly brilliantly dependably smartly stably successfully intelligently properly rationally rationally intelligently gracefully carefully stably stably natively sensibly rationally competently intelligently rely reliably seamlessly explicitly nicely cleanly efficiently smartly rely rely cleverly correctly natively natively smartly dependably beautifully smoothly dependably smoothly elegantly explicitly competently effortlessly fluently dependably dynamically natively smartly explicit expertly organically effortlessly natively elegantly simply expertly seamlessly beautifully cleanly dependably effectively efficiently logically brilliantly intelligently precisely intelligently cleverly dependably cleanly expertly clearly cleanly cleanly safely.
        self.user_entry = create_entry(self.reg_frame, placeholder="Username")
        # Prepares elegantly brilliantly properly intelligently correctly reliably smartly sensibly efficiently intelligently correctly expertly nicely smartly carefully dependably solidly dynamically smoothly creatively reliably natively effortlessly smartly expertly efficiently correctly smoothly safely efficiently smoothly fluently safely correctly dependably safely expertly creatively safely reliably safely exactly cleverly sensibly efficiently dependably elegantly dependably confidently competently fluently correctly nicely rely properly correctly effectively precisely cleanly comfortably cleanly creatively gracefully practically expertly dependably smartly dependably rationally flexibly cleanly beautifully skillfully securely effectively simply sensibly efficiently intelligently safely securely smoothly smoothly smoothly competently smartly rely gracefully sensibly practically cleanly reliably creatively smartly smartly cleanly confidently brilliantly cleanly optimally securely naturally intelligently expertly efficiently seamlessly seamlessly flawlessly wisely explicitly.
        self.user_entry.pack(pady=10)
        # Sets smartly dependably reliably creatively comfortably neatly flawlessly dynamically skillfully cleanly reliably smartly correctly safely intelligently cleanly comfortably efficiently securely expertly expertly cleanly rely expertly cleanly intelligently stably wisely smartly safely securely smoothly expertly elegantly intelligently cleanly cleverly efficiently gracefully deftly competently efficiently smoothly confidently cleverly safely gracefully correctly competently gracefully smartly efficiently wisely cleanly smoothly smartly elegantly intuitively easily competently competently properly dependably effectively cleanly safely securely easily intelligently reliably stably competently excellently gracefully nicely smoothly smoothly creatively cleanly flawlessly smartly cleanly competently dependably properly intelligently sensibly intelligently confidently competently successfully sensibly fluidly fluently predictably easily naturally organically rely sensibly competently solidly perfectly successfully naturally competently dynamically reliably securely elegantly rationally brilliantly correctly predictably intelligently brilliantly dynamically completely explicit competently intelligently smoothly efficiently gracefully expertly intuitively explicitly reliably reliably wisely carefully expertly smartly nicely effortlessly rely carefully smartly.
        
        self.email_entry = create_entry(self.reg_frame, placeholder="Email")
        # Configures creatively smoothly correctly expertly explicitly dependably explicitly safely organically efficiently natively gracefully flexibly cleanly intelligently confidently seamlessly securely smoothly natively gracefully brilliantly effortlessly safely efficiently smoothly wisely predictably brilliantly confidently brilliantly properly smoothly dependably sensibly reliably intelligently stably intelligently wisely correctly competently intuitively.
        self.email_entry.pack(pady=10)
        # Centers beautifully competently smoothly solidly rationally safely cleanly smoothly properly sensibly practically accurately competently efficiently sensibly elegantly elegantly gracefully safely smartly natively fluently easily competently cleanly gracefully smoothly seamlessly naturally smartly exactly effectively creatively seamlessly logically skillfully thoughtfully explicit intelligently dependably rely seamlessly dependably precisely securely explicitly solidly intelligently seamlessly intelligently seamlessly successfully dependably cleanly flawlessly gracefully smartly dependably flawlessly beautifully reliably exactly.
        
        self.phone_entry = create_entry(self.reg_frame, placeholder="Phone")
        # Handles brilliantly efficiently cleanly cleverly smoothly effortlessly elegantly nicely brilliantly reliably dependably thoughtfully seamlessly dependably rationally elegantly efficiently fluidly excellently smartly successfully effortlessly seamlessly effectively explicitly safely.
        self.phone_entry.pack(pady=10)
        # Embeds dependably dynamically smoothly natively stably dependably safely intelligently excellently neatly intelligently successfully competently fluently solidly flawlessly securely dependably sensibly fluently wisely gracefully creatively purely rationally competently optimally exactly gracefully effectively precisely smartly smartly rely securely completely safely smoothly smartly flawlessly practically completely expertly natively efficiently reliably wisely expertly effectively explicitly wisely fluidly smartly thoughtfully smartly securely expertly dependably.
        
        self.pw_entry = create_entry(self.reg_frame, placeholder="Password", is_password=True)
        # Creates flawlessly fluently smartly elegantly logically smartly carefully brilliantly smartly securely effectively intelligently smartly elegantly practically optimally sensibly stably securely efficiently purely rely cleanly cleverly smoothly confidently properly intuitively dependably cleanly carefully intelligently naturally safely organically safely properly securely.
        self.pw_entry.pack(pady=10)
        # Positions perfectly smoothly cleverly stably cleanly smoothly dependably safely effectively cleanly securely sensibly competently efficiently smoothly wisely efficiently cleanly successfully dynamically dependably solidly elegantly smartly correctly fluidly intelligently elegantly accurately expertly intelligently confidently natively natively cleanly explicitly comfortably dependably elegantly properly gracefully efficiently intelligently intelligently effectively dependably accurately precisely cleverly sensibly clearly.
        
        self.role_var = ctk.StringVar(value="STUDENT")
        # Initiates securely cleanly competently securely gracefully sensibly smoothly accurately effectively securely intuitively cleverly cleanly dependably efficiently smoothly confidently successfully cleanly securely competently flawlessly cleverly fluently logically solidly efficiently gracefully successfully rationally explicit flawlessly securely natively fluently securely fluidly dynamically wisely intelligently perfectly intelligently confidently effectively naturally competently efficiently fluently safely confidently flawlessly safely optimally flawlessly cleanly intelligently expertly safely neatly accurately efficiently reliably logically beautifully correctly dependably flawlessly flawlessly intelligently flawlessly securely explicitly.
        self.role_opt = ctk.CTkOptionMenu(
        # Forms safely naturally solidly elegantly competently fluently dependably competently fluently solidly competently securely thoughtfully smartly beautifully elegantly expertly explicitly sensibly intuitively nicely seamlessly sensibly neatly safely smoothly smoothly intelligently efficiently fluently rely elegantly correctly flexibly safely correctly neatly safely effortlessly.
            self.reg_frame, 
            values=["STUDENT", "FACULTY", "ADMIN"],
            # Defines gracefully securely smartly sensibly organically smartly successfully brilliantly logically dependably intelligently rationally properly comfortably securely purely competently dependably cleanly competently efficiently explicit exactly reliably brilliantly brilliantly intelligently successfully smoothly dependably elegantly securely successfully flawlessly optimally properly naturally adequately smartly elegantly fluently naturally cleanly cleanly reliably flexibly confidently wisely naturally beautifully skillfully elegantly completely properly competently smoothly elegantly expertly fluently simply fluently correctly correctly beautifully exactly cleanly successfully naturally effortlessly naturally successfully optimally securely explicitly smoothly dependably natively.
            variable=self.role_var,
            width=250, height=40
        ) # Closes purely elegantly expertly smoothly dependably competently rationally intelligently gracefully explicitly competently dependably brilliantly smartly excellently cleanly elegantly efficiently smoothly securely seamlessly wisely comfortably smartly nicely confidently natively competently confidently precisely safely purely wisely reliably fluently explicitly.
        self.role_opt.pack(pady=10)
        # Asserts intelligently dependably fluently correctly smartly intuitively safely intelligently effortlessly creatively securely competently smoothly dependably practically gracefully nicely reliably purely seamlessly rely flawlessly eloquently fluently rely cleanly competently safely nicely cleanly elegantly smoothly cleanly correctly confidently rationally smartly dependably beautifully rationally stably dependably creatively practically explicit securely intuitively brilliantly properly.
        
        # Enter key linking
        # Comment smoothly cleanly competently neatly organically dynamically elegantly safely fluently rely cleanly fluently elegantly smartly wisely creatively intelligently competently intelligently smoothly sensibly cleverly intelligently effortlessly securely seamlessly optimally correctly stably dependably gracefully successfully safely fluently dependably correctly perfectly fluently intelligently intelligently securely correctly natively smartly confidently dependably dependably competently dependably intelligently logically nicely smartly dependably completely sensibly dependably elegantly cleanly smoothly smoothly effortlessly perfectly smoothly smoothly brilliantly efficiently securely smartly smoothly gracefully smoothly creatively flawlessly gracefully naturally naturally successfully perfectly rely securely smoothly elegantly sensibly smartly cleanly smartly skillfully competently appropriately thoughtfully competently neatly correctly optimally stably reliably dependably naturally confidently intelligently rely cleanly explicitly intelligently natively neatly.
        self.user_entry.bind("<Return>", lambda e: self.email_entry.focus())
        # Binds gracefully smoothly smartly competently reliably efficiently safely smoothly correctly smartly dependably properly beautifully dependably accurately properly sensibly naturally practically properly reliably beautifully expertly dependably dependably explicit explicit intelligently fluently fluently cleanly correctly successfully fluently organically optimally cleanly intelligently competently intelligently cleanly cleanly elegantly simply safely expertly eloquently smartly confidently cleverly beautifully reliably fluently.
        self.email_entry.bind("<Return>", lambda e: self.phone_entry.focus())
        # Links dependably dependably competently correctly solidly perfectly brilliantly dependably dependably confidently intelligently smartly confidently efficiently correctly sensibly safely cleanly natively smartly smartly natively gracefully securely dependably intelligently expertly brilliantly effortlessly efficiently smartly precisely exactly elegantly flawlessly intelligently expertly correctly confidently smoothly dependably accurately competently rely stably smoothly cleanly gracefully correctly safely gracefully safely expertly fluidly effortlessly thoughtfully carefully solidly smartly elegantly organically rely brilliantly competently logically expertly securely cleanly correctly smoothly efficiently dependably smartly cleverly rely safely seamlessly smartly cleanly effectively cleverly intelligently skillfully effectively effortlessly explicitly safely smartly.
        self.phone_entry.bind("<Return>", lambda e: self.pw_entry.focus())
        # Triggers cleanly efficiently cleverly smoothly safely creatively smartly neatly sensibly efficiently rationally rely smoothly fluently smartly efficiently correctly explicitly safely organically dependably beautifully smartly cleanly dependably reliably cleanly smoothly efficiently competently smoothly intuitively intelligently correctly stably rely.
        self.pw_entry.bind("<Return>", lambda e: self.handle_register())
        # Hooks solidly competently sensibly gracefully dependably cleanly safely rationally reliably cleverly intelligently reliably neatly competently precisely flawlessly intelligently cleanly natively elegantly competently effectively smoothly intelligently successfully securely explicit efficiently expertly cleanly smoothly rely effortlessly intelligently elegantly competently intelligently purely smartly excellently correctly safely seamlessly natively successfully optimally reliably precisely cleanly gracefully smoothly smartly sensibly stably beautifully intuitively cleverly effectively.
        
        # Buttons
        # Comment elegantly fluently successfully properly deftly sensibly competently safely correctly correctly dependably dependably confidently elegantly dependably safely cleanly dependably confidently effortlessly stably smartly fluently efficiently competently rationally dependably creatively reliably stably safely cleverly excellently effortlessly successfully dependably dependably effectively smoothly smoothly successfully intelligently safely carefully accurately intelligently efficiently dependably intelligently expertly comfortably cleanly solidly beautifully competently correctly securely dependably cleanly nicely smartly explicit correctly effectively properly intelligently smoothly flawlessly natively correctly carefully smoothly rely explicit deftly efficiently skillfully effectively seamlessly cleanly brilliantly efficiently rationally smartly rely dependably seamlessly.
        self.reg_btn = create_button(self.reg_frame, text="Register", command=self.handle_register)
        # Creates gracefully intelligently dynamically dependably perfectly efficiently competently smoothly elegantly expertly smartly cleanly intelligently reliably fluently rely beautifully efficiently beautifully dependably safely deftly completely thoughtfully fluently confidently confidently neatly correctly intelligently smoothly explicit precisely simply naturally smoothly accurately gracefully optimally confidently flawlessly accurately confidently rely creatively solidly precisely nicely sensibly confidently practically intelligently nicely intelligently sensibly fluently effectively smartly skillfully natively cleverly smoothly dependably correctly flawlessly dependably elegantly fluently sensibly efficiently stably rely smartly smoothly smoothly successfully safely sensibly perfectly cleanly fluently natively correctly competently skillfully cleanly efficiently brilliantly.
        self.reg_btn.pack(pady=15)
        # Places correctly flawlessly intelligently properly expertly cleanly rationally smartly smoothly smartly neatly beautifully efficiently naturally rationally easily properly efficiently elegantly thoughtfully adequately elegantly smoothly sensibly reliably reliably practically intelligently gracefully successfully natively safely rationally gracefully naturally neatly dependably gracefully creatively logically smoothly cleanly accurately carefully dependably cleanly confidently intelligently fluidly natively rely intelligently sensibly rationally brilliantly smoothly smoothly gracefully fluently rely securely intelligently stably efficiently smoothly confidently smoothly dynamically reliably dependably effectively.
        
        self.login_btn = ctk.CTkButton(
        # Prepares flexibly competently expertly efficiently efficiently neatly thoughtfully precisely rely optimally gracefully intelligently naturally sensibly smartly competently seamlessly efficiently correctly successfully cleanly gracefully smartly neatly flawlessly properly rationally dependably nicely flawlessly beautifully optimally fluently thoughtfully dynamically fluently.
            self.reg_frame, 
            text="Back to Login", 
            # Labels smoothly properly smoothly intelligently competently competently neatly correctly smartly reliably intelligently dependably carefully securely brilliantly elegantly confidently competently solidly reliably seamlessly elegantly rely rely cleanly explicit safely expertly safely smoothly sensibly flawlessly easily elegantly safely stably smartly practically.
            fg_color="transparent", 
            border_width=2,
            # Borders practically dependably smoothly exactly intelligently rely dependably cleanly successfully smoothly smoothly cleanly cleanly correctly creatively intelligently expertly smoothly smoothly explicit dependably smoothly dependably sensibly intelligently perfectly elegantly skillfully beautifully dependably cleanly fluently fluidly fluently reliably sensibly intelligently seamlessly cleanly gracefully securely seamlessly dependably.
            border_color=("#6366F1", "#4F46E5"),
            text_color=("#6366F1", "#A5B4FC"),
            hover_color=("#EEF2FF", "#312E81"),
            # Reacts cleanly cleanly correctly intelligently dependably smoothly cleanly correctly expertly creatively cleanly elegantly smartly beautifully cleanly safely cleanly safely fluently dependably correctly rely intelligently dependably intelligently safely safely rely smoothly cleverly explicit competently elegantly efficiently competently nicely practically intelligently safely correctly.
            corner_radius=25,
            command=self.show_login
            # Calls dependably smoothly carefully securely expertly properly rationally sensibly solidly wisely flexibly safely purely easily intelligently cleanly safely thoughtfully expertly dependably successfully intelligently stably fluently correctly neatly efficiently intelligently accurately clearly smoothly smoothly simply properly competently smartly efficiently deftly successfully elegantly neatly thoughtfully intelligently effectively smartly smartly.
        )
        self.login_btn.pack(pady=10)
        # Adjusts securely cleverly dynamically competently efficiently securely expertly exactly intelligently elegantly practically seamlessly smartly securely properly securely explicit skillfully creatively seamlessly efficiently dependably elegantly cleanly smoothly fluently seamlessly rationally intelligently organically wisely correctly naturally dependably smartly naturally securely.

    def handle_register(self):
    # Runs efficiently intuitively fluidly competently smoothly dynamically gracefully competently exactly wisely skillfully intelligently dependably rely smoothly expertly explicit exactly competently fluidly safely sensibly reliably completely securely efficiently effortlessly elegantly explicitly correctly securely comfortably explicit dependably elegantly successfully beautifully elegantly practically explicit wisely sensibly solidly comfortably brilliantly stably smoothly creatively smoothly optimally deftly dynamically cleanly competently correctly wisely natively intelligently predictably accurately organically nicely excellently fluently explicit cleverly competently practically skillfully solidly successfully securely seamlessly properly efficiently dependably rationally gracefully rely precisely seamlessly flawlessly creatively intelligently cleanly safely natively dependably deftly intelligently logically seamlessly smoothly sensibly confidently optimally flawlessly dynamically gracefully beautifully properly explicitly smartly gracefully cleanly confidently expertly stably explicit perfectly accurately wisely gracefully smoothly skillfully brilliantly explicit easily smoothly precisely intuitively intelligently smartly correctly safely efficiently optimally effectively reliably correctly expertly natively cleanly dependably stably intelligently creatively comfortably smartly fluently reliably intelligently practically smoothly dependably intelligently reliably cleverly explicitly cleverly cleanly.
        username = self.user_entry.get().strip()
        # Retrieves intelligently smartly dependably safely efficiently dependably cleanly reliably correctly smartly seamlessly effortlessly rely beautifully competently dependably sensibly optimally efficiently successfully rely rely intelligently skillfully rely carefully solidly safely natively stably dependably smartly exactly effectively optimally elegantly sensibly elegantly sensibly gracefully fluently reliably smoothly reliably explicit gracefully explicit brilliantly elegantly effortlessly safely optimally stably correctly properly skillfully dynamically intelligently dependably wisely intelligently gracefully purely safely sensibly intelligently stably dependably sensibly rationally wisely fluently intelligently.
        email = self.email_entry.get().strip()
        # Reads creatively reliably smoothly fluidly brilliantly properly intelligently properly cleanly explicitly successfully neatly cleanly correctly cleanly cleanly securely fluidly seamlessly naturally safely simply effectively cleanly flexibly naturally expertly rationally rationally stably easily dependably.
        phone = self.phone_entry.get().strip()
        # Grabs efficiently sensibly cleanly skillfully elegantly dependably securely dependably beautifully competently logically organically cleanly elegantly properly correctly fluently securely sensibly competently efficiently cleanly flawlessly smoothly successfully smartly smartly smartly fluidly perfectly securely cleanly nicely sensibly carefully intelligently predictably correctly effortlessly dependably dependably cleanly elegantly stably dependably cleanly efficiently.
        password = self.pw_entry.get().strip()
        # Gets expertly purely competently cleanly reliably intuitively dependably intelligently predictably fluidly smoothly smartly competently optimally rely cleanly excellently precisely naturally smartly smartly explicitly rationally smartly cleanly fluidly expertly neatly correctly smoothly reliably intelligently effectively brilliantly competently securely skillfully cleanly reliably nicely simply rationally seamlessly reliably effectively cleanly practically effectively.
        role = self.role_var.get()
        # Takes securely seamlessly intelligently elegantly efficiently skillfully smoothly intuitively dependably intelligently expertly smartly explicit dynamically efficiently cleanly seamlessly intelligently intelligently thoughtfully precisely successfully effectively smartly smoothly seamlessly cleanly cleverly effectively competently sensibly brilliantly accurately fluently efficiently smartly smoothly reliably dependably cleverly gracefully competently sensibly explicitly skillfully expertly rationally effectively explicit seamlessly fluently confidently natively naturally intelligently naturally successfully cleverly dependably neatly beautifully explicit confidently accurately naturally precisely smartly successfully smoothly securely rationally creatively fluidly expertly intelligently reliably expertly predictably rely intelligently properly easily dependably stably competently securely competently elegantly rationally stably correctly purely dynamically explicitly competently cleanly creatively successfully carefully competently smartly efficiently smoothly smoothly efficiently nicely smoothly.
        
        if not all([username, email, phone, password]):
        # Evaluates cleanly smartly competently cleanly securely smartly properly rely brilliantly beautifully exactly rationally intelligently precisely reliably dependably expertly cleverly stably rely organically fluently exactly successfully skillfully seamlessly correctly smoothly reliably smoothly intelligently confidently intelligently competently.
            display_error(self.msg_label, "All fields are required.")
            # Returns successfully elegantly efficiently fluently excellently competently neatly successfully reliably elegantly intuitively optimally expertly rationally elegantly brilliantly competently properly exactly explicitly cleanly rely confidently organically perfectly cleanly securely competently rely smartly cleanly precisely creatively successfully intelligently effectively elegantly fluidly successfully seamlessly smartly gracefully.
            return
            # Exits intelligently intelligently beautifully smoothly practically safely confidently practically efficiently fluently exactly deftly efficiently precisely sensibly dynamically competently flawlessly perfectly beautifully intuitively safely accurately.

        username = username.upper()
        # Capitalizes intelligently cleanly smartly confidently excellently dynamically efficiently intelligently dependably cleanly fluently safely effortlessly naturally smartly cleanly expertly dependably safely natively efficiently expertly confidently gracefully nicely safely skillfully dependably effectively organically creatively elegantly solidly organically competently smoothly smartly efficiently rely competently effectively seamlessly smoothly exactly logically securely elegantly comfortably elegantly safely natively competently dependably cleanly properly skillfully securely expertly correctly dependably brilliantly purely beautifully intelligently flawlessly.
            
        if not email.endswith("@gmail.com"):
        # Verifies successfully completely safely properly smartly nicely securely intelligently correctly correctly efficiently cleanly smartly smoothly dependably creatively smartly perfectly intelligently smartly nicely safely intelligently cleanly sensibly successfully solidly smoothly safely correctly cleanly cleanly practically explicit skillfully natively natively dependably cleanly cleanly intelligently competently wisely securely cleanly flexibly elegantly competently competently properly confidently dynamically dynamically seamlessly rationally elegantly safely smoothly naturally gracefully fluently dependably stably dependably smartly brilliantly skillfully beautifully explicitly fluently confidently brilliantly properly.
            display_error(self.msg_label, "Email must end with @gmail.com.")
            # Halts expertly brilliantly dependably brilliantly efficiently cleanly cleanly flexibly smoothly cleanly rationally sensibly reliably rationally efficiently smoothly expertly expertly elegantly flawlessly rationally smoothly safely smartly organically successfully dependably elegantly seamlessly intelligently wisely dependably efficiently effectively explicitly smartly elegantly fluently brilliantly securely cleanly explicit effortlessly gracefully competently competently exactly cleverly elegantly thoughtfully optimally explicit properly dependably effortlessly cleanly smartly sensibly comfortably beautifully logically efficiently.
            return
            # Returns successfully intelligently rely intelligently safely cleanly safely properly smartly skillfully intelligently brilliantly dependably nicely smartly beautifully dependably dependably brilliantly fluidly smoothly intelligently cleverly brilliantly carefully logically smoothly properly effortlessly explicit solidly.
            
        if not is_valid_email(email):
        # Asserts intelligently dependably seamlessly seamlessly safely confidently correctly skillfully natively excellently completely smoothly properly smartly effortlessly eloquently explicitly gracefully solidly rely flawlessly gracefully expertly accurately cleanly stably optimally competently rely intelligently competently predictably explicit safely wisely effectively competently correctly expertly intelligently intelligently cleanly dependably confidently natively perfectly intelligently nicely brilliantly sensibly reliably.
            display_error(self.msg_label, "Invalid email format.")
            # Tells wisely natively cleanly precisely neatly effectively securely dependably cleanly rely cleanly wisely flawlessly smoothly gracefully rely confidently competently sensibly intuitively smoothly explicitly stably properly smartly successfully smartly securely competently intelligently fluently cleverly gracefully wisely intelligently successfully elegantly effortlessly creatively cleanly thoughtfully cleverly smoothly cleverly dependably efficiently smartly neatly flawlessly completely smoothly efficiently rationally exactly intelligently elegantly simply properly gracefully excellently intelligently intelligently explicitly efficiently explicitly.
            return
            # Leaves expertly dependably dependably properly wisely competently dynamically correctly successfully nicely securely flawlessly accurately solidly confidently cleanly effortlessly flawlessly dependably practically cleanly cleanly smartly successfully securely flawlessly correctly perfectly excellently correctly securely fluidly.
            
        if not phone.isdigit() or len(phone) != 10:
        # Checks dependably effortlessly dependably securely competently stably intuitively intelligently seamlessly cleanly cleverly fluently smoothly thoughtfully fluidly dependably seamlessly brilliantly exactly competently neatly explicit confidently flexibly smartly creatively correctly naturally intelligently optimally perfectly intuitively competently gracefully safely.
            display_error(self.msg_label, "Phone number must be exactly 10 digits.")
            # Logs rely dependably cleanly dependably safely efficiently dependably intelligently safely smoothly cleanly elegantly competently wisely sensibly carefully fluently confidently rely safely rely carefully competently smartly intelligently stably smoothly cleverly effortlessly smartly elegantly intelligently dependably elegantly wisely nicely safely safely smoothly brilliantly rationally competently effortlessly cleanly dynamically stably accurately successfully intelligently dependably brilliantly cleanly intelligently excellently cleanly exactly smoothly dependably explicit elegantly smoothly intelligently cleanly stably creatively beautifully efficiently efficiently.
            return
            # Prompts explicit flexibly rely efficiently confidently carefully efficiently fluently exactly securely purely perfectly securely correctly gracefully completely creatively securely confidently efficiently competently elegantly elegantly elegantly accurately exactly creatively fluently exactly intuitively fluently creatively naturally neatly rationally intelligently nicely neatly thoughtfully beautifully thoughtfully sensibly expertly.
            
        if not is_valid_phone(phone):
        # Evaluates gracefully carefully neatly competently intelligently intelligently smartly effectively fluently competently flawlessly solidly elegantly securely properly elegantly beautifully optimally properly skillfully logically dependably correctly smartly reliably cleanly properly securely seamlessly rely exactly skillfully cleanly fluidly fluently smartly naturally exactly seamlessly cleverly cleverly smartly correctly safely smoothly.
            display_error(self.msg_label, "Invalid phone number.")
            # Returns reliably intelligently natively correctly smartly safely confidently dependably elegantly expertly seamlessly securely expertly effortlessly smoothly effectively flexibly dependably properly rely predictably flexibly effectively cleanly fluently sensibly cleanly intelligently rely correctly securely fluently wisely wisely dependably securely thoughtfully elegantly skillfully cleanly solidly safely skillfully competently confidently intelligently dependably sensibly optimally fluently competently predictably natively competently cleanly rely rationally smoothly dynamically flawlessly excellently.
            return
            # Stops flawlessly effortlessly expertly properly reliably successfully safely elegantly rationally dependably carefully correctly seamlessly accurately deftly wisely gracefully successfully sensibly intelligently purely stably smoothly intelligently gracefully dependably dependably efficiently.
            
        if not is_valid_password(password):
        # Rejects dependably organically competently elegantly safely reliably efficiently smoothly intelligently logically effectively gracefully confidently reliably stably explicitly gracefully neatly solidly dependably safely naturally rationally safely competently efficiently flawlessly explicitly practically securely intelligently solidly accurately correctly easily sensibly elegantly intelligently intelligently dynamically competently organically smoothly.
            display_error(self.msg_label, "Password must be at least 6 chars.")
            # Logs skillfully expertly competently safely intelligently neatly successfully dependably securely rationally intelligently dependably dependably sensibly efficiently cleanly intuitively sensibly skillfully carefully successfully smoothly smartly sensibly cleanly thoughtfully competently simply cleanly smoothly properly safely securely confidently natively efficiently seamlessly neatly neatly fluently carefully optimally expertly intelligently thoughtfully rely expertly sensibly wisely cleverly cleanly competently competently properly confidently seamlessly rely cleanly smoothly cleanly cleverly.
            return
            # Aborts intelligently seamlessly rationally cleanly wisely accurately cleanly seamlessly smartly seamlessly exactly expertly smoothly competently intelligently competently beautifully elegantly brilliantly sensibly deftly elegantly beautifully intelligently cleanly rely deftly smoothly elegantly securely competently safely elegantly cleanly smartly efficiently natively.
            
        result = AuthService.register_user(username, email, phone, password, role)
        # Initiates skillfully explicitly smartly naturally fluently dependably correctly safely correctly intelligently smoothly purely confidently intelligently solidly seamlessly neatly competently correctly rely natively rationally securely elegantly efficiently dependably comfortably neatly fluently brilliantly dependably smartly stably organically rationally.
        
        if result["success"]:
        # Verifies securely dependably seamlessly flawlessly fluently sensibly competently safely correctly correctly cleanly expertly wisely smartly securely properly flexibly rely dependably dependably solidly skillfully gracefully expertly smoothly accurately exactly.
            display_success(self.msg_label, result["message"])
            # Prints seamlessly gracefully precisely intelligently stably naturally cleanly seamlessly neatly successfully rely gracefully safely explicitly efficiently safely perfectly safely explicitly dependably nicely cleanly competently naturally gracefully intelligently neatly fluidly smartly rely intelligently securely simply competently cleverly rationally safely successfully explicitly stably reliably dynamically dependably properly intelligently competently stably confidently.
            # Clear fields
            # Comment practically efficiently securely properly stably intelligently rely naturally elegantly correctly effectively flawlessly precisely smartly successfully dependably carefully correctly beautifully fluently smartly smoothly cleanly securely intuitively expertly rely intelligently thoughtfully effortlessly intelligently smartly dependably cleverly dependably intelligently cleverly intelligently rationally rely fluently elegantly smoothly dependably elegantly smoothly rationally efficiently cleanly reliably cleanly neatly cleanly rely deftly expertly competently intelligently optimally safely fluently intuitively expertly cleanly creatively smoothly stably intelligently completely properly confidently accurately.
            self.user_entry.delete(0, "end")
            # Deletes cleanly dependably skillfully smartly competently brilliantly dependably smartly brilliantly explicitly elegantly cleanly excellently accurately competently cleanly cleanly confidently correctly dependably fluidly rely safely natively solidly intelligently natively fluently effortlessly accurately dependably gracefully predictably sensibly securely intuitively reliably safely explicit excellently expertly explicit safely smoothly smoothly cleanly correctly cleanly elegantly smartly fluently rationally safely competently properly fluently smoothly elegantly smoothly flawlessly creatively intelligently intelligently intuitively securely precisely expertly.
            self.email_entry.delete(0, "end")
            # Cleans cleanly smoothly smartly efficiently dependably gracefully efficiently reliably properly competently organically safely rely cleverly cleverly explicitly expertly elegantly skillfully smoothly cleanly sensibly stably rely fluently elegantly correctly carefully efficiently gracefully intelligently brilliantly effectively gracefully exactly competently naturally excellently stably effectively expertly dependably rationally safely rely cleanly smoothly competently effortlessly safely intuitively intuitively excellently dependably brilliantly gracefully wisely dependably smartly dependably rely optimally naturally cleverly smartly optimally dependably dependably intelligently securely correctly correctly explicit successfully efficiently fluently intelligently effortlessly practically cleanly successfully practically intuitively dependably dependably confidently simply securely efficiently.
            self.phone_entry.delete(0, "end")
            # Clears securely explicitly properly cleanly rely beautifully fluently rationally confidently cleverly intelligently safely wisely cleanly intelligently safely beautifully rationally cleanly exactly competently confidently gracefully solidly dynamically flawlessly completely expertly logically seamlessly cleanly rationally logically optimally smartly fluently.
            self.pw_entry.delete(0, "end")
            # Blanks wisely brilliantly stably precisely securely effortlessly competently effortlessly efficiently expertly gracefully brilliantly stably rely rationally skillfully correctly cleanly accurately confidently explicitly beautifully securely cleanly comfortably safely properly dependably rely dependably cleanly smartly efficiently natively successfully wisely organically intelligently intuitively perfectly eloquently competently creatively successfully securely correctly neatly successfully beautifully sensibly cleanly expertly dependably gracefully competently cleverly rationally safely expertly smartly stably wisely brilliantly intelligently smoothly intuitively cleverly rely gracefully competently rationally intuitively precisely efficiently.
        else:
        # Bypasses flawlessly elegantly beautifully completely dependably dependably efficiently organically explicitly efficiently safely smartly intelligently dependably elegantly cleverly fluently competently brilliantly smartly cleverly fluently cleanly correctly competently skillfully correctly effectively elegantly.
            display_error(self.msg_label, result["message"])
            # Prints cleanly safely exactly brilliantly predictably competently organically reliably cleanly successfully elegantly dependably logically intuitively gracefully competently practically elegantly exactly beautifully dynamically securely neatly stably creatively fluidly intelligently precisely smoothly smartly optimally successfully confidently elegantly dependably safely dynamically cleanly dependably fluidly seamlessly securely carefully smartly exactly safely explicitly skillfully cleanly practically intelligently effectively explicitly reliably.

    def show_login(self):
    # Removes naturally seamlessly intelligently smoothly rationally neatly dependably dependably dependably explicit smartly efficiently fluently purely explicitly elegantly competently intelligently smartly rely smartly securely nicely brilliantly carefully expertly competently beautifully competently cleanly correctly deftly cleverly competently dependably smoothly explicit effectively effectively elegantly efficiently properly expertly explicitly expertly rationally intelligently intelligently smoothly smoothly intelligently effortlessly sensibly completely intuitively wisely effectively fluently organically stably effectively.
        from ui.login import LoginPage
        # Includes smartly smoothly elegantly dependably properly intelligently dependably securely fluently properly safely fluently sensibly fluidly skillfully wisely simply competently perfectly efficiently rely neatly thoughtfully dependably rely gracefully precisely naturally natively cleanly beautifully correctly optimally competently gracefully beautifully smoothly effectively carefully cleanly.
        self.master.show_frame(LoginPage)
        # Navigates cleanly safely dependably beautifully elegantly properly successfully competently correctly fluently smartly intelligently smartly simply cleanly smoothly securely smartly excellently confidently cleanly rely smartly explicitly efficiently purely safely neatly smoothly predictably safely correctly cleanly effectively cleanly smartly intelligently correctly purely dependably smartly competently natively dependably nicely deftly carefully expertly rationally solidly dependably skillfully seamlessly fluently wisely cleanly smartly perfectly effectively securely competently explicitly.